### ISSUE TITLE
Breaking vacuum hopper crashes minecraft

### ISSUE THREAD

**Issue by ABruel** [lucaargolo/kibe#104] opened 2021-09-26 19:29 UTC
The game crashed whilst rendering block entity
Error: java.lang.IllegalArgumentException: Cannot get property class_2746{name=enabled, clazz=class java.lang.Boolean, values=[true, false]} as it does not exist in Block{minecraft:air}
Código de saída: -1

Playing on all of fabric 4 modpack.

**Comment by lucaargolo** [comment] 2021-09-28 05:54
Please send the full crash report. Only one line doesn't tell me anything.

**Comment by lucaargolo** [comment] 2022-10-09 18:30
Closing this since I wasn't able to reproduce it and no one else reported it.

**Closed as completed by lucaargolo** 2022-10-09 18:30 UTC
Labels: bug, question
