### ISSUE TITLE
Chunk Loader prevents soil hydration and crop growth

### ISSUE THREAD

**Issue by ceasefyre** [lucaargolo/kibe#120] opened 2021-12-10 15:02 UTC
Crops and soil blocks within range of kibe chunkloader do not auto-hydrate despite being within range of water. Also, no crop growth updates happen, newly planted crops on hydrated farmland with sufficient light stay at 0% no matter the amount of time lapsed.

**Comment by Stelk** [comment] 2021-12-14 22:47
I'm observing the same behavior.  on 1.18 branch.  Maybe similar to this issue in anther mod? https://github.com/TheCBProject/ChickenChunks/issues/52

**Comment by wackoamd1** [comment] 2021-12-15 10:20
yes im having the same problem , incl. trees and when u remove the chunkloader u have to unload the chunks by disconnecting from server before the things start to grow again

**Comment by Luizfelz** [comment] 2021-12-21 02:23
Hi guys. 

First, I'm having the same problem. When I put a Chunkloader, it prevents: crops growth (and sapplings), hydration of soil, grass spreading on dirt and leaf decay. 

But, I'm commenting here because I found another interaction with the chunkloader. I realized that if you are playing with the Bewitchment mod, when you summon a Demon you won't be able to trade with them if you have a chunkloader "loading" the altar (and/or the demons). When you break the chunkloader, everything goes back to normal and you can trade again. I didn't know if I needed to post this on Bewitchment mod github or here, so I took this Issue already created to comment here.

**Comment by Pluettmann** [comment] 2021-12-26 13:09
I can confirm the problem with tree and crop growth

**Comment by JacobDB** [comment] 2022-01-03 20:51
Same with sugar cane

**Comment by octagonalsquare** [comment] 2022-02-01 03:41
Is there a known fix? Because I have computercraft turtles that farm trees but need to be able to leave the area

**Comment by lucaargolo** [comment] 2022-02-28 08:42
This should be fixed in the latest 1.9.5 release!

**Closed as completed by lucaargolo** 2022-02-28 08:42 UTC
Labels: bug
