### ISSUE TITLE
Crash when a mob dies to spikes

### ISSUE THREAD

**Issue by RSAmaro** [lucaargolo/kibe#133] opened 2022-01-24 03:19 UTC
Just like the title says, I was building a mob farm, and for some reason, everytime a mob dies, it just crashes the server.

Modpack: Benchmark II 0.6.5

Crash Log
[crash.txt](https://github.com/lucaargolo/kibe/files/7922609/crash.txt)

**Comment by lucaargolo** [comment] 2022-01-24 04:18
Please don't post crash reports directly in the issue message, it's horrible to read, just upload the file. Also this is being caused by PlayerEvents. They're casting all PlayerEntities to ServerPlayerEntities without actually checking if they're ServerPlayerEntities.
https://github.com/ByMartrixx/player-events/blob/ed4108f2de03bb10d5481730b0094f0c6d4a8cdb/api/src/main/java/me/bymartrixx/playerevents/api/mixin/PlayerKillEntityMixin.java#L24
If they just change `(entity instanceof PlayerEntity)` to `(entity instanceof ServerPlayerEntity)` this would be fixed, and the code would be even cleaner cause those two casts could be avoided.

**Comment by vaporvee** [comment] 2022-01-30 17:02
So this can be fixed in a future kibe update? or can only PlayerEvents fix this?

**Comment by lucaargolo** [comment] 2022-01-30 21:38
PlayerEvents needs to fix it as changing my FakePlayer to a ServerPlayerEntity would break functionality with some features.

**Comment by vaporvee** [comment] 2022-02-22 14:12
you can close this now it was fixed

**Closed as completed** 2022-02-28 08:45 UTC
Labels: mod incompatibility
