### ISSUE TITLE
Broken Stuck Redstone Timer

### ISSUE THREAD

**Issue by KyGost** [lucaargolo/kibe#105] opened 2021-09-28 05:27 UTC
Rarely there is an issue that can occur which causes redstone times to be stuck at a 1tick pulse and be indestructable-- indestructable in that *nothing* can remove them. Neither creative nor `setblock` nor worldedit.

It is very possible that this is a [MCMT](https://github.com/himekifee/MCMTFabric) issue. If so please don't feel cause to patch/investigate.

Has anyone else experienced this?

**Comment by lucaargolo** [comment] 2021-09-28 05:53
IIRC I already saw someone reporting this same thing happening before, but since I was never able to reproduce it and it was only one person that didn't even bring the issue directly to me I let it slide. If you manage to find out how to reliably reproduce it, it would be greatly appreciated.

**Comment by KyGost** [comment] 2021-09-29 04:43
> IIRC I already saw someone reporting this same thing happening before, but since I was never able to reproduce it and it was only one person that didn't even bring the issue directly to me I let it slide. If you manage to find out how to reliably reproduce it, it would be greatly appreciated.

Will try! Don't get any logging for it but will see what happens.
Failing observing I might take a pair of fresh eyes to the codebase and see if I can think of something that might cause it.

**Comment by lucaargolo** [comment] 2022-10-09 18:30
Closing this since I wasn't able to reproduce it and no one else reported it.

**Closed as completed by lucaargolo** 2022-10-09 18:30 UTC
Labels: bug, help wanted
