### ISSUE TITLE
glider is not working

### ISSUE THREAD

**Issue by wilibago** [lucaargolo/kibe#111] opened 2021-10-16 19:49 UTC
im trying the modpack benchmark on cursedforge and i cant use the gliders when i right click i equip it but cant glide with it

**Comment by lucaargolo** [comment] 2022-02-28 08:48
Is this still reproducible in the latest release? I wasn't able to do it so I'm thinking it probably was some kind of cursed mod incompatibility.

**Comment by lucaargolo** [comment] 2022-10-09 18:30
Closing this since I wasn't able to reproduce it and no one else reported it.

**Closed as completed by lucaargolo** 2022-10-09 18:30 UTC
Labels: bug, mod incompatibility
